### ISSUE TITLE
More Information

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry-incubator/diego-ssh#1]
Hi guys,

I deploy diego-release and cf-release and ssh-proxy is activated.
I have one docker application/container running under diego now I would like to ssh using the ssh proxy.

But some of the requirement, documentation are not so clear 

>The user is of the form diego:process-guid/index and the password must hold the receptor credentials in the form user:password.
>Client example:
>```bash ssh -p 2222 'diego:my-process-guid/1'@ssh.10.244.0.34.xip.io```
>The user and password used by the proxy are extracted from the diegoAPIURL that is specified on the command line. If the user info field is empty, the password will be empty as well.

For CF for example what is  : 
* ``` diego:process-guid ``` Should I always keep ``` diego: ``` but what is the process-guid ? Application guid ?
*  ``` password must hold the receptor credentials in the form user:password. ``` No idea about this one
* ``` User and password used by the proxy are extracted from the diegoAPIURL that is specified on the command line``` No idea too about this one.

I can give some input I have

``` cf app lattice```
``` 
 {
      "guid": "c5cb762b-b7bb-44b6-97d1-2b612d4baba9",
      "urls": [
        "lattice.10.244.0.34.xip.io"
      ],
      "routes": [
        {
          "guid": "6c60b124-4bf2-4ab2-a29e-f3d312f73397",
          "host": "lattice",
          "domain": {
            "guid": "da695d93-e866-4dab-bb40-9b4a7308d9a0",
            "name": "10.244.0.34.xip.io"
          }
        }
      ],
      "service_count": 0,
      "service_names": [

      ],
      "running_instances": 1,
      "name": "lattice",
      "production": false,
      "space_guid": "3c910823-22e7-41ff-98de-094759594398",
      "stack_guid": "ea50566f-a63c-4e10-a45f-bb6e919cb540",
      "buildpack": null,
      "detected_buildpack": null,
      "environment_json": {

      },
      "memory": 256,
      "instances": 1,
      "disk_quota": 1024,
      "state": "STARTED",
      "version": "addeac53-e7b2-400f-be0e-0f6df40f1d08",
      "command": null,
      "console": false,
      "debug": null,
      "staging_task_id": "6fb6699ed7084196ac545bf17de6255f",
      "package_state": "STAGED",
      "health_check_type": "port",
      "health_check_timeout": null,
      "staging_failed_reason": null,
      "diego": true,
      "docker_image": "cloudfoundry/lattice-app:latest",
      "package_updated_at": "2015-05-13T03:28:53Z",
      "detected_start_command": "/lattice-app ",
      "enable_ssh": false
    }
```

``` cf curl "/v3/processes" ```
```
{
         "guid": "c5cb762b-b7bb-44b6-97d1-2b612d4baba9",
         "type": "web",
         "command": null,
         "instances": 1,
         "created_at": "2015-05-13T03:20:41Z",
         "updated_at": "2015-05-27T08:40:26Z",
         "_links": {
            "self": {
               "href": "/v3/processes/c5cb762b-b7bb-44b6-97d1-2b612d4baba9"
            },
            "scale": {
               "href": "/v3/processes/c5cb762b-b7bb-44b6-97d1-2b612d4baba9/scale",
               "method": "PUT"
            },
            "app": {
               "href": "/v3/apps/"
            },
            "space": {
               "href": "/v2/spaces/3c910823-22e7-41ff-98de-094759594398"
            }
         }
      },
```

Thanks

**Comment by ematpl** [comment]
Hi, @shinji62,

You're correct, we should add instructions for the CF-specific authentication mechanism to this README and the other Diego documentation. For now, I'll explain how it works here:

- To connect to a CF app over SSH, use the username `cf:<app-guid>/<index>`, where `<app-guid>` is the guid of the app and `<index>` is the index of the instance you intend to connect to.
- The password for this user is any valid OAuth token for a user with access to that app (for example, a space developer in the app's space). You can generate a new token from the CF CLI with `cf oauth-token`; the token is the content starting with `bearer` and including the following base64-encoded payload.
- The hostname, port, and host key fingerprint are exposed through fields in the response from CC's `/v2/info` endpoint.
- For a given CF deployment, the Diego SSH proxies must also be exposed via a load balancer for them to receive external traffic. If CF is deployed to use the HAproxy job in cf-release and ssh support is enabled in the CF deployment manifest, the HAproxy configuration will be updated dynamically to balance across all the SSH proxies. This is the case for a default BOSH-Lite deployment. If that HAproxy job is not used, a load balancer and DNS must instead be set up with the IaaS provider. This is commonly the case on AWS and on other IaaSes that provide load balancing as a service.

Eventually, the `cf ssh` plugin will handle all of this transparently for users of the CF CLI. Those stories are currently prioritized in the CLI tracker backlog, with the [first one](https://www.pivotaltracker.com/story/show/90425212) in flight now.

The instructions for the standalone Diego authenticator are more appropriate when working at the level of Diego's receptor API. The `process-guid` in this context is the process guid of the DesiredLRP submitted to the receptor; for a CF app, this process-guid value is `<app-guid>-<app-version>`. The user and password are those required for basic authentication to the receptor API, which the proxy determines from the `-diegoAPIURL` flag passed to it when it is started.

Best,
Eric, CF Runtime Diego PM

**Comment by shinji62** [comment]
Thanks.
I tested the provided ssh plugin and it works.
