### ISSUE TITLE
Dependency vendoring

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry-incubator/diego-ssh#19]
Would it be possible to add the vendored dependencies of diego-ssh to this repo, possibly in the form of Godeps?
I had an issue with `github.com/pkg/sftp`, where there occured a breaking change for diego-ssh and I had to guess which commit was still OK.

**Comment by sykesm** [comment]
@JamesClonk the [diego-release](https://github.com/cloudfoundry-incubator/diego-release) tree is where we vendor dependencies for diego. We used to use Godeps but have moved towards a strategy where our release tree is treated as our GOPATH and all of the vendored dependencies are submodules.

Out of curiosity, are you trying to use this code outside of Cloud Foundry?

Thanks.

**Comment by JamesClonk** [comment]
@sykesm Ah ok, didn't know that. Thanks!
No, I'm not using this code outside of CF.
