### ISSUE TITLE
diego-ssh hardcodes metron port to be 3457

### ISSUE THREAD

**Issue by roxtar** [cloudfoundry-incubator/diego-ssh#7]
diego-ssh [hardcodes the metron port to be 3457](https://github.com/cloudfoundry-incubator/diego-ssh/blob/master/cmd/ssh-proxy/main.go#L83)

The metron port can be configured in CloudFoundry to be something other than 3457, so a change to the metron port will break metrics.

**Comment by ematpl** [comment]
Hi, @roxtar,

The Diego team will address this across the release in https://www.pivotaltracker.com/story/show/103689460, so I'l close this issue out in favor of that.

Thanks,
Eric
