### ISSUE TITLE
Can't ssh into windows instance

### ISSUE THREAD

**Issue by JackXuF** [cloudfoundry-incubator/diego-ssh#9]
rejected: administratively prohibited (SSH is not supported on windows cells)   
 Do you support ssh into windows cell's instance?

**Comment by ematpl** [comment]
Hi, @JackXuF,

Thanks for asking! We don't currently support SSH access to Windows instances, although the CF Greenhouse team has a story at https://www.pivotaltracker.com/story/show/100162006 to provide it at some point. @sbenario and @benmoss from that team may know more about current plans for support.

Best,
Eric, CF Runtime Diego PM

**Comment by benmoss** [comment]
Yep, making the SSH client work on Windows is a non-trivial amount of work due to the lack of PTY in Windows. We have this in our targets for the future, but it's not currently a top priority.

**Comment by ematpl** [comment]
Closing, as we don't intend to fix this in the near future, and there's work represented in the Greenhouse tracker around making it available eventually.
